name: Deploy Website
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # - name: Manually Set Global ENVs
    #   run: |
    #     echo 'process.env.CI=false' >> $GITHUB_ENV
    - name: Extract branch name from commit
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      id: extract_branch
    - name: Extract branch name from PR
      if: github.event_name == 'pull_request'
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
    - name: Print branch name
      run: echo 'The branch name is' $BRANCH_NAME
    - name: Manually Load Environment File
      run: cat env.demo >> $GITHUB_ENV
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Deploy site build to S3 bucket
      run: | 
        aws s3 cp *.html s3://${S3_BUCKET}/${BRANCH_NAME}/